### ISSUE TITLE
Prototypal Features and Terms

### ISSUE THREAD

**Issue by jhaemin** [woowa-techcamp-2020/todo-14#2]
This issue describes the prototypal features and the terms of the software which are being used across the entire development routine.
## 용어

- **Board**: 전체 투두 보드
- **Card**: 단일 ToDo 작업
- **Column**: Card의 집합체
- **Activity**: Card나 Column의 변경 사항의 기록
- **Menu**: Activity 내역을 담고 있는 우측에서 나타나는 사이드 바

### 컬럼 (column)

- [x] 컬럼 이름 수정 (#6)
- [x] 새 카드 버튼 (#4)
- [x] 새 컬럼 추가 (#3)
- [x] 컬럼 삭제 (x 버튼) (#7)
- [x] 컬럼에 해당되는 전체 카드 개수 (#8)

### 카드 (card)

- [x] 카드 생성 (내용 입력 및 확인) (#5)
- [x] 컨텐츠 (첫 줄은 제목)
- [ ] 작성자 표시 (공유 보드) (won't implement)
- [x] 카드 아이콘 (변경 가능)
- [x] 삭제 (#11)
- [x] 카드 클릭 시 수정 (확인/취소 버튼) (#9)
- [x] 드래그&드롭 (#10)

### 메뉴 (활동 기록)

- 날짜 표시 (friendly date)
- Column
  - 추가
  - 삭제
  - 이름 수정
  - 이동
- Card
  - 추가
  - 삭제
  - 수정
  - 이동
- 중요 키워드 강조 (유저, 제목)

## DB Schema

<img width="1511" alt="Screen Shot 2020-07-14 at 5 48 59 PM" src="https://user-images.githubusercontent.com/19797697/87405403-5b270080-c5fa-11ea-861b-7d10d12de246.png">
